### ISSUE TITLE
Interaction with Kestrel in self-hosted console app

### ISSUE THREAD

**Issue by harvellm** [cloudtoid/interprocess#11]
Hi!  I have a working monitoring process using this great library.  Today I decided that I was going to add a self-hosted API through Kestrel...something very simple and something I have done many times before.  However, I am finding a couple of really odd issues:  First, the processing works fine with these additions but Kestrel just returns no data.  The controllers are getting called, and that is the second issue, they are getting called multiple times for one GET request.  So I pulled my hair figuring it all out and ended up commenting out everything but the WebHostBuilder configuration. When I remove this nuget package, and that is the only change, the controller behaves perfectly fine - one call, and returns data.  Simply adding this package back into the project and the weird behavior begins.

Any ideas?

**Comment by harvellm** [comment]
I have found more.  I modified my WebHostBuilder configuration to the following:

![image](https://user-images.githubusercontent.com/748312/135348213-c13edfc4-e6ef-414d-8a6a-d7124a8669bd.png)

and here is the stack trace:

```
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.CreateResponseHeader(Boolean appCompleted)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProduceStart(Boolean appCompleted)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.InitializeResponseAsync(Int32 firstWriteByteCount)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WriteAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, Encoding encoding, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, CancellationToken cancellationToken)
   at selfhosting.Program.<>c.<<Main>b__1_1>d.MoveNext() in C:\Users\rr277019\source\repos\MGH-CLIs\namedpipestest\selfhosting\selfhosting\Program.cs:line 27
```

If I do nothing else but remove the Interprocess library then there is no error.

**Comment by prezaei** [comment]
Thanks. Got a repo by any chance I could play in? @harvellm

**Comment by harvellm** [comment]
Thanks, man.  Yeah, I'll upload a repo tomorrow that is simple and which won't make my boss kill me. :). I really appreciate the help, I mean it - your lib is awesome.  I just don't understand what is going on here because when I look through your code I don't see what could be the issue.  I'll have something up by mid-day Chicago time tomorrow :). Appreciate it.

**Comment by harvellm** [comment]
Good day!  Here is the repo:  https://github.com/harvellm/selfhosting 

Note that I took all the code that actually uses this library out - it works fine.  It is just the fact that the library is included in the project that causes the problem.  I'll add some screenshots to outline my testing below.

**Comment by prezaei** [comment]
Thank you for going through the trouble. I will certainly look into it this week or this weekend. Thanks again.

**Comment by prezaei** [comment]
@harvellm, looks like your `csproj` is not setup correctly. Try the following changes:

```diff
-<Project Sdk="Microsoft.NET.Sdk">
+<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

-  <ItemGroup>
-    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
-    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.2.0" />
-    <PackageReference Include="Microsoft.NETCore.App" Version="2.2.8" />
-  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\selfhosting.lib\selfhosting.lib.csproj" />
  </ItemGroup>

</Project>
```
