### ISSUE TITLE
Unhandled exception when multi subscribers

### ISSUE THREAD

**Issue by PeterLukAtPulsar** [cloudtoid/interprocess#14]
under window 10 C# net6
version: 1.0.169

Created a simple publisher/subscriber test and working perfectly for 1P1C mode (P-producer, C- consumer)
however, when trying 1P2C mode, get the following exception after a short while in one of consumers

```
Unhandled exception. System.InvalidOperationException: This is unexpected and can be a serious bug. We take a lock on this message prior to this point which should ensure that the HeadOffset is left unchanged.
   at Cloudtoid.Interprocess.Subscriber.TryDequeueImpl(Nullable`1 resultBuffer, CancellationToken cancellation, ReadOnlyMemory`1& message)
   at Cloudtoid.Interprocess.Subscriber.TryDequeueCore(Nullable`1 resultBuffer, CancellationToken cancellation, ReadOnlyMemory`1& message)
   at Cloudtoid.Interprocess.Subscriber.TryDequeue(Memory`1 resultBuffer, CancellationToken cancellation, ReadOnlyMemory`1& message)

```

**Comment by prezaei** [comment]
Hey @PeterLukAtPulsar , do you happen to have a repro? Thanks

**Comment by prezaei** [comment]
There is a PR out to fix this issue, @PeterLukAtPulsar.
