### ISSUE TITLE
Ubuntu - System.DllNotFoundException: Unable to load shared library 'librt' 

### ISSUE THREAD

**Issue by ericbrunner** [cloudtoid/interprocess#3]
Hi,

Can you please help me with that error. I just created a sample on TFM .NET 5.0 and get that exception on Ubuntu WSL (WIndows Subsystem for Linux) on Window 10.

Sample: https://zone-eric@dev.azure.com/zone-eric/NET%20Core%20Crossplattform%20IPC/_git/NETCoreXplatIPC 

Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

System.DllNotFoundException: Unable to load shared library 'librt' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibrt: cannot open shared object file: No such file or directory
   at Cloudtoid.Interprocess.Semaphore.Linux.Interop.sem_open(String name, Int32 oflag, UInt32 mode, UInt32 value)
   at Cloudtoid.Interprocess.Semaphore.Linux.Interop.CreateOrOpenSemaphore(String name, UInt32 initialCount)
   at Cloudtoid.Interprocess.Semaphore.Linux.SemaphoreLinux..ctor(String name, Boolean deleteOnDispose)
   at Cloudtoid.Interprocess.InterprocessSemaphore.CreateWaiter(String name)
   at Cloudtoid.Interprocess.Subscriber..ctor(QueueOptions options, ILoggerFactory loggerFactory)
   at Cloudtoid.Interprocess.QueueFactory.CreateSubscriber(QueueOptions options)
   at Sunify.WorkerService.Worker.ExecuteAsync(CancellationToken stoppingToken) in /home/eric/source/repos/NETCoreXplatIPC/xPlat-IPC/Sunify.WorkerService/Worker.cs:line 26
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Sunify.WorkerService.Program.Main(String[] args) in /home/eric/source/repos/NETCoreXplatIPC/xPlat-IPC/Sunify.WorkerService/Program.cs:line 15

Full command line log is here: https://gist.github.com/ericbrunner/cd2122fad75920cdb758735cce0bb220

**Comment by prezaei** [comment]
Sorry for the delay. Is this still an issue?

**Comment by prezaei** [comment]
Seems to be an issue still.

**Comment by prezaei** [comment]
This is now fixed
